#!/bin/bash

if 
  ls | grep Scanning
then 
    echo
  else
    mkdir Scanning
  fi

echo -e '\e[38;5;208m enter ip address to scan ';
read ip

if 
  ls -R | grep Scanning/$ip
then 
  echo
  else
    mkdir -p Scanning/$ip
  fi

dir=Scanning/$ip

nmap_open_ports () {
    nmap --open $ip -oN $dir/nmap_open_ports.txt
    clear
}

nmap_list_interfaces () {
    nmap --iflist $ip -oN $dir/nmap_list_interfaces.txt
    clear
}
nmap_slow () {
    sudo nmap -sS -v -T1 $ip -oN $dir/nmap_slow-$ip.txt
    clear
}
nmap_fin () {
    sudo nmap -sF -v $ip -oN $dir/nmap_fin-$ip.txt
    clear
}
nmap_full () {
    sudo nmap -sS -T4 -PE -PP -PS80,443 -PY -g 53 -A -p1-65535 -v $ip -oN $dir/nmap_full-$ip.txt
    clear
}
nmap_check_for_firewall () {
    sudo nmap -sA -p1-65535 -v -T4 $ip -oN $dir/nmap_check_for_firewall-$ip.txt
    clear
}
nmap_ping_through_firewall (){
    nmap -PS -PA $ip -oN $dir/nmap_ping_through_firewall-$ip.txt
    clear
}
nmap_fast () {
    nmap -F -T5 --version-light --top-ports 300 $ip -oN $dir/nmap_fast-$ip.txt
    clear
}
nmap_detect_version () {
    sudo nmap -sV -p1-65535 -O --osscan-guess -T4 -Pn $ip -oN $dir/nmap_detect_version-$ip.txt
    clear 
}
nmap_check_for_vulns () {
    nmap -sV--script=vuln $ip -oN $dir/nmap_check_for_vulns-$ip.txt
    clear
}
nmap_full_udp () {
    sudo nmap -sS -sU -T4 -A -v -PE -PS22,25,80 -PA21,23,80,443,3389 $ip -oN $dir/nmap_full_udp-$ip.txt
    clear
}
nmap_traceroute () {
    sudo nmap -sP -PE -PS22,25,80 -PA21,23,80,3389 -PU -PO --traceroute $ip -oN $dir/nmap_traceroute-$ip.txt
    clear
}
nmap_full_with_scripts () {
    sudo nmap -sS -sU -T4 -A -v -PE -PP -PS21,22,23,25,80,113,31339 -PA80,113,443,10042 -PO --script all $ip -oN $dir/nmap_full_with_scripts-$ip.txt
    clear
}
nmap_web_safe_osscan () {
    sudo nmap -p 80,443 -O -v --osscan-guess --fuzzy $ip -oN $dir/nmap_web_safe_osscan-$ip.txt
    clear
}
nmap_ping_scan () {
    nmap -n -sP $ip -oN $dir/nmap_ping_scan-$ip.txt
    clear
}
nmap_use_all () {
    echo "Running nmap_open_ports"
    nmap --open $ip -oN $dir/nmap_open_ports.txt && clear
    echo "Running nmap_list_interfaces"
    nmap --iflist $ip -oN $dir/nmap_list_interfaces.txt && clear
    echo "Running nmap_slow"
    sudo nmap -sS -v -T1 $ip -oN $dir/nmap_slow-$ip.txt && clear
    echo "Running nmap_fin"
    sudo nmap -sF -v $ip -oN $dir/nmap_fin-$ip.txt && clear
    echo "Running nmap_full"
    sudo nmap -sS -T4 -PE -PP -PS80,443 -PY -g 53 -A -p1-65535 -v $ip -oN $dir/nmap_full-$ip.txt && clear
    echo " Running nmap_check_for_firewall"
    sudo nmap -sA -p1-65535 -v -T4 $ip -oN $dir/nmap_check_for_firewall-$ip.txt && clear
    echo " Running nmap_ping_through_firewall"
    nmap -PS -PA $ip -oN $dir/nmap_ping_through_firewall-$ip.txt && clear
    echo "Running nmap_fast"
    nmap -F -T5 --version-light --top-ports 300 $ip -oN $dir/nmap_fast-$ip.txt && clear
    echo " Running nmap_detect_version"
    sudo nmap -sV -p1-65535 -O --osscan-guess -T4 -Pn $ip -oN $dir/nmap_detect_version-$ip.txt && clean
    echo "Running nmap_check_for_vulns"
    nmap -sV--script=vuln $ip -oN $dir/nmap_check_for_vulns-$ip.txt && clear
    echo " Running nmap_full_udp"
    sudo nmap -sS -sU -T4 -A -v -PE -PS22,25,80 -PA21,23,80,443,3389 $ip -oN $dir/nmap_full_udp-$ip.txt && clear
    echo " Running nmap_traceroute"
    sudo nmap -sP -PE -PS22,25,80 -PA21,23,80,3389 -PU -PO --traceroute $ip -oN $dir/nmap_traceroute-$ip.txt && clear
    echo " Running nmap_full_with_scripts"
    sudo nmap -sS -sU -T4 -A -v -PE -PP -PS21,22,23,25,80,113,31339 -PA80,113,443,10042 -PO --script all $ip -oN $dir/nmap_full_with_scripts-$ip.txt && clear
    echo " Running nmap_web_safe_osscan"
    sudo nmap -p 80,443 -O -v --osscan-guess --fuzzy $ip -oN $dir/nmap_web_safe_osscan-$ip.txt && clear
    echo " Running nmap_ping_scan"
    nmap -n -sP $ip -oN $dir/nmap_ping_scan-$ip.txt
}

while true; do
    options=("nmap_open_ports" 
            "nmap_list_interfaces" 
            "nmap_slow" 
            "nmap_fin" 
            "nmap_full" 
            "nmap_check_for_firewall" 
            "nmap_ping_through_firewall" 
            "nmap_fast" 
            "nmap_detect_version" 
            "nmap_check_for_vulns" 
            "nmap_full_udp" 
            "nmap_traceroute" 
            "nmap_full_with_scripts" 
            "nmap_web_safe_osscan" 
            "nmap_ping_scan"
            "nmap_use_all" 
            "Quit")
logo(){

echo    '                                                                                                     ';
echo -e '\e[38;5;88m  #     #    #     #####  #    #  #####  ####### ### ######  '; 
echo -e '\e[38;5;88m  #     #   # #   #     # #   #  #     #    #     #  #     # ';
echo -e '\e[38;5;215m  #     #  #   #  #       #  #   #          #     #  #     # ';
echo -e '\e[38;5;215m  ####### ####### #       ###     #####     #     #  ######  ';
echo -e '\e[38;5;208m  #     # #     # #       #  #         #    #     #  #       ';
echo -e '\e[38;5;208m  #     # #     # #     # #   #  #     #    #     #  #       ';
echo -e '\e[38;5;208m  #     # #     #  #####  #    #  #####     #    ### #       ';
echo    '                                                                                                       ';

echo -e '\e[38;5;208m        Automated Nmap cheat sheet  <3 Muzammil ( hackstip.com )          ';
}

logo



    PS3='Please enter your choice: '
    select opt in "${options[@]}"; do
        case $REPLY in
            1)  nmap_open_ports; break ;;
            2)  nmap_list_interfaces; break ;;
            3)  nmap_slow; break ;;
            4)  nmap_fin ; break;;
            5)  nmap_full; break;;
            6)  nmap_check_for_firewall; break;;
            7)  nmap_ping_through_firewall; break;; 
            8)  nmap_fast; break;;
            9)  nmap_detect_version; break;;
            10) nmap_check_for_vulns; break;;
            11) nmap_full_udp; break;;
            12) nmap_traceroute; break;; 
            13) nmap_full_with_scripts; break;; 
            14) nmap_web_safe_osscan; break;;
            15) nmap_ping_scan; break;;
            16) nmap_use_all; break ;;
            17) break 2 ;; 
            *) echo "Please Enter An Options Provided" >&2
        esac
    done
done

echo "Bye bye!"